### ISSUE TITLE
AirBnBRating not persisting state on parent

### ISSUE THREAD

**Issue by rubensbarreto** [Monte9/react-native-ratings#10]
Opening the issue referencing the unresolved state problems on:
#9

**Comment by Monte9** [comment]
Hi @rubensbarreto! Yes, you are right. I see the error.

The problem is not with this library but in fact with the way you are using `this.state`. 

You first need to create a state in the constructor and only then can you store something on the state. Also since `ratingCompleted` is a callback function, you need to bind it in the constructor as well. is a Try this code instead:

```
constructor(){
  super()

  this.state = {
    rating: null
  }

  this.ratingCompleted = this.ratingCompleted.bind(this)
}

ratingCompleted(rating) {
  console.log('Rating is: ' + rating);

  this.setState({
    rating: rating
  });
}
```

**Comment by Monte9** [comment]
I have tried this in my app and can verify that it works. Hope this helps you!
